---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api
  namespace: services
  labels:
    app: ticket-api
    service: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-api
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
        - name: ticket-api
          image: ticket-api:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ticket-configmap
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 516Mi
      restartPolicy: Always
