---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ticket-configmap
  namespace: hpc-services
data:

  # application context
  APPLICATION_CONTEXT: /api/tickets/v3

  # version of OpenAPI
  OPENAPI: 3:0.3

  # the application providing info about the ticket
  TICKET_CLIENT_APP: https://hpc.asml.com/portal

  # atlassian website
  ATLASSIAN_URL: https://asml-it-ccb-bdbi.atlassian.net

  # Jira settings
  JIRA_TICKET_TYPE: Task
  JIRA_TICKET_LABELS: test,support,rteixeir
  JIRA_TICKET_LABEL_CATEGORIES: general,storage
  JIRA_TICKET_LABEL_DEFAULT_CATEGORY: general

  # Jira supported boards
  JIRA_BOARDS: JIRA_SPRINT_BOARD,JIRA_SUPPORT_BOARD
  JIRA_SPRINT_BOARD: HPC
  JIRA_SUPPORT_BOARD: HPC-support
  JIRA_DEFAULT_BOARD: JIRA_SUPPORT_BOARD

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api-service
  namespace: hpc-services
  labels:
    app: ticket-api-service
    service: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-api-service
  template:
    metadata:
      labels:
        app: ticket-api-service
    spec:
      containers:
        - name: ticket-api-service
          image: cdl-hadoop-artifactory.asml.com/hpc/services/ticket-api:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ticket-configmap
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 1
              memory: 516Mi
      restartPolicy: Always
