---
steps:
  - label: ":package: Package repository"
    command: ".buildkite/steps/kaniko/package.sh"
    agents:
      env: kubernetes
      namespace: services
      privileged: false

  - wait

  - trigger: "kaniko"
    label: ":buildkite: Trigger build pipeline"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: HEAD
      branch: "${BUILDKITE_BRANCH}"
      env:
        REGISTRY: renato.jfrog.io
        REGISTRY_REPOSITORY: local-docker
        IMAGE_NAME: ticket-service
        IMAGE_TAG: latest