---
steps:
  - label: ":docker: :kubernetes: Build image"
    command: .buildkite/scripts/build.sh
    concurrency: 1
    concurrency_group: ticket-service/build
    branches: master
    agents:
      env: kubernetes
      namespace: buildkite-agent
      privileged: true
      kaniko: true