---
steps:
  - label: ":docker: :kubernetes: Build image"
    command: .buildkite/scripts/build.sh
    branches: master
    agents:
      env: kubernetes
      namespace: buildkite-agent
      privileged: true
      kaniko: true