---
apiVersion: v1
kind: Pod
metadata:
  name: ticket-bridge
  labels:
    app: ticket-bridge
    framework: flask
  annotations:
    a8r.io/description: "Batch service for creating tickets out of mailbox events"
    a8r.io/owner: renatodamas
spec:
  imagePullSecrets:
    - name: registry-credentials
  containers:
    - name: ticket-job
      image: ${IMAGE}:${TAG}
      imagePullPolicy: Always
      command: [ "flask", "o365", "handle-incoming-email" ]
      envFrom:
        - configMapRef:
            name: ticket
        - secretRef:
            name: ticket
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
  restartPolicy: OnFailure