---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - configmap.yaml
  - sa.yaml
  - rbac.yaml
images:
  - name: ticket-service
    newName: ...
    newTag: latest